version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "MitulShah1"
    labels:
      - "dependencies"
      - "go"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "MitulShah1"
    labels:
      - "github-actions"
      - "ci-cd"
